###
### Assets
###

# Listar assets
POST http://localhost:3000/api/assets

###

# Criar asset
GET http://localhost:3000/api/assets?id=1&symbol=XYZ

###

###
### Orders
###

# Listar orders
GET http://localhost:3000/api/orders

###

# Criar order
POST http://localhost:3000/api/orders

Content-Type: application/json

{
  "asset_id": 1,
  "price": 10.5
}
